"""empty message

Revision ID: e3eb44a156aa
Revises: 24f4c587a4c7
Create Date: 2020-12-30 12:20:56.194170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3eb44a156aa'
down_revision = '24f4c587a4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
